### ISSUE TITLE
Fotos de la presentacion

### ISSUE THREAD

**Issue by GeroBecker** [pdepviernestm/2024-presentacion-FrancoBenedetti1907#2]
Buenas! Considero que hacen falta más fotos en la presentación, para facilitar esto recomiendo que adjuntes tu Instagram a la misma, saludos!

**Comment by ghost** [comment]
Hola Gero ! . No se muy  bien como adjuntar mi instagram ya que no conozco muy bien la sintaxis de este lenguaje . Pero podes pedirselo a un intagrante de tu familia en particular que se que lo tiene . Saludos !!
